logging:
    level:
        org.bitcoinj: ERROR

neo4j:
    neo4jUrl: "http://localhost:7474/db/data/"  
    neo4jUsername: "neo4j"
    neo4jPassword: "Iz0von0f"

server:
    url: http://localhost:8080
    imagePath: /images
    imageFolder: images

blockchain:
    confirmations: 1
    feesThreshold: 20
    fees: 0.1
    walletFolder: "wallet"
    walletName: "centralWallet"
    adminUsername: "wallet@yope.io"
    adminPassword: "ag4jal0o"

security.basic.enabled: false

keystore.file: "src/main/resources/private/keystorejks"
keystore.pass: "password"

backend:
    admin:
        username: "backend_admin"
        password: "backend_admin"
        role: "BACKEND_ADMIN"