logging:
    level:
        org.bitcoinj: ERROR

neo4j:
    neo4jUrl: "http://localhost:7474/db/data/"  
    neo4jUsername: "neo4j"
    neo4jPassword: "Iz0von0f"
server:
    url: http://localhost:8080
    imagePath: /images
    imageFolder: images
blockchain:
    confirmations: 3